<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

	<PropertyGroup>
		<NuGetAuditLevel>critical</NuGetAuditLevel>
		<InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Bunit</InterceptorsPreviewNamespaces>
	</PropertyGroup>

	<ItemGroup Condition="$(MSBuildProjectName) != 'LinkDotNet.Blog.TestUtilities'">
		<PackageReference Include="xunit.v3" />
		<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="bunit" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="NSubstitute" />
	</ItemGroup>

	<ItemGroup Condition="$(MSBuildProjectName) != 'LinkDotNet.Blog.TestUtilities'">
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup Label="Implicit usings">
		<Using Include="Shouldly" />
		<Using Include="NSubstitute" />
		<Using Include="Bunit" />
		<Using Include="Bunit.TestDoubles" />
	</ItemGroup>

</Project>
