/// <autogenerated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LinkDotNet.Blog.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BlogPostRecords",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    BlogPostId = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    DateClicked = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    Clicks = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BlogPostRecords", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "BlogPosts",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    Title = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    ShortDescription = table.Column<string>(type: "TEXT", nullable: false),
                    Content = table.Column<string>(type: "TEXT", nullable: false),
                    PreviewImageUrl = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: false),
                    PreviewImageUrlFallback = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "TEXT", nullable: false),
                    ScheduledPublishDate = table.Column<DateTime>(type: "TEXT", nullable: true),
                    Tags = table.Column<string>(type: "TEXT", maxLength: 2048, nullable: false),
                    IsPublished = table.Column<bool>(type: "INTEGER", nullable: false),
                    Likes = table.Column<int>(type: "INTEGER", nullable: false),
                    ReadingTimeInMinutes = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BlogPosts", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ProfileInformationEntries",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    Content = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false),
                    SortOrder = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ProfileInformationEntries", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ShortCodes",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    MarkdownContent = table.Column<string>(type: "TEXT", nullable: false),
                    Name = table.Column<string>(type: "TEXT", maxLength: 512, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ShortCodes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SimilarBlogPosts",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    SimilarBlogPostIds = table.Column<string>(type: "TEXT", maxLength: 1350, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SimilarBlogPosts", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Skills",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    IconUrl = table.Column<string>(type: "TEXT", maxLength: 1024, nullable: true),
                    Name = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    Capability = table.Column<string>(type: "TEXT", maxLength: 128, nullable: false),
                    ProficiencyLevel = table.Column<string>(type: "TEXT", maxLength: 32, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Skills", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Talks",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    PresentationTitle = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    Place = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false),
                    Description = table.Column<string>(type: "TEXT", nullable: false),
                    PublishedDate = table.Column<DateTime>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Talks", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "UserRecords",
                columns: table => new
                {
                    Id = table.Column<string>(type: "TEXT", unicode: false, nullable: false),
                    DateClicked = table.Column<DateOnly>(type: "TEXT", nullable: false),
                    UrlClicked = table.Column<string>(type: "TEXT", maxLength: 256, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserRecords", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_BlogPosts_IsPublished_UpdatedDate",
                table: "BlogPosts",
                columns: new[] { "IsPublished", "UpdatedDate" },
                descending: new[] { false, true });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BlogPostRecords");

            migrationBuilder.DropTable(
                name: "BlogPosts");

            migrationBuilder.DropTable(
                name: "ProfileInformationEntries");

            migrationBuilder.DropTable(
                name: "ShortCodes");

            migrationBuilder.DropTable(
                name: "SimilarBlogPosts");

            migrationBuilder.DropTable(
                name: "Skills");

            migrationBuilder.DropTable(
                name: "Talks");

            migrationBuilder.DropTable(
                name: "UserRecords");
        }
    }
}
